# Linear Algebra

In [21]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [22]:
# Transpose
a.T

array([[1, 3],
       [2, 4]])

In [23]:
# divide each element to an scalar
print ("a/2 =\n", a / 2) # or np.divide(a, 2)

a/2 =
 [[0.5 1. ]
 [1.5 2. ]]


In [24]:
# The largest integer smaller or equal to the division of the inputs.
print ("a/2 (floor) =\n", np.floor_divide(a, 2)) 

a/2 (floor) =
 [[0 1]
 [1 2]]


In [25]:
# Practical usage:
farenheit = np.array([0, 10, -5, 4])
celcius = (farenheit - 31) * (5/9)
print("celcius = ", celcius)

celcius =  [-17.22222222 -11.66666667 -20.         -15.        ]


In [26]:
a

array([[1, 2],
       [3, 4]])

In [27]:
b = np.array([[2, 3], [4, 5]])
b

array([[2, 3],
       [4, 5]])

In [28]:
# Adding Matrices
a + b # or np.add(a, b)

array([[3, 5],
       [7, 9]])

In [29]:
# Subtracting matrices
b - a # or np.subtract(b, a)

array([[1, 1],
       [1, 1]])

In [30]:
# Element-by-element multiplication: [ 1*2, 2*3], [3*4, 4*5]]
a * b # or np.multiply(a, b)

array([[ 2,  6],
       [12, 20]])

In [31]:
# Element-by-elemnt division 
print ("b/a =\n", b / a) # or np.divide(b, a)

b/a =
 [[2.         1.5       ]
 [1.33333333 1.25      ]]


In [32]:
# Identity matrix
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

**dot product**

In [33]:
A = np.array([1, 2])
B = np.array([3, 4])
np.dot(A, B)

11

**Matrix Product** <br>
sum of the multiplication of row elements to column element<br>
Example: $a \times a = [[1\times 1 + 2\times 3, 1\times 2 + 2\times 4], [3\times 1 + 4\times 3, 3\times 2 + 4\times 4]]$<br>
The general operator is @, however you can also use ```matmul``` function of numpy to get the matrix product of two arrays.

In [34]:
print("a@b=\n", a@b)
print("np.matmul(a, b)=\n", np.matmul(a, b))

a@b=
 [[10 13]
 [22 29]]
np.matmul(a, b)=
 [[10 13]
 [22 29]]


Multiple chained multiplication is also available for square matrix. The function ```matrix_power``` raises a square matrix to the (integer) power n. <br>
For positive integers $n$, the power is computed by repeated matrix multiplications. If $n = 0$, the identity matrix of the same shape as M is returned. If $n<0$, the inverse is computed and then raised to the $|n|$.

In [35]:
np.linalg.matrix_power(a, 2)

array([[ 7, 10],
       [15, 22]])

In [36]:
np.linalg.matrix_power(a, 0)

array([[1, 0],
       [0, 1]])

In [37]:
np.linalg.matrix_power(a, 3)

array([[ 37,  54],
       [ 81, 118]])

In [38]:
# Trace
np.trace(a)

5

In [39]:
# Determinant
np.linalg.det(a)

-2.0000000000000004

In [40]:
# Rank
np.linalg.matrix_rank(a)

2

**Inverse**

In [41]:
def inverse(arr):
    det = np.linalg.det(arr)
    rank = np.linalg.matrix_rank(arr)
    if det == 0:
        print(f"Inverse doesn't exist. Determinant is zero. Rank = {rank} for a {arr.shape} matrix")
    else:
        print(f"determinant = {det}, rank = {rank} (full ranked)")
        print(np.linalg.inv(arr))

In [42]:
z = np.array([[1, 1, 1], [1, 1, 2], [1, 1, 3]])
inverse(z)

Inverse doesn't exist. Determinant is zero. Rank = 2 for a (3, 3) matrix


In [43]:
x = np.array([[1, 1, 2],
              [3, -3, -1],
              [2, -1, 6]])
inverse(x)

determinant = -33.0, rank = 3 (full ranked)
[[ 0.57575758  0.24242424 -0.15151515]
 [ 0.60606061 -0.06060606 -0.21212121]
 [-0.09090909 -0.09090909  0.18181818]]


**Equation Solving**

In [44]:
from numpy.linalg import LinAlgError

y = np.array([12, 3, 24])
try:
    print(np.linalg.solve(x, y))
except LinAlgError:
    print("No Solution")

[4. 2. 3.]


**Vector Norms**

In [45]:
# L2-norm
arr = np.array([3, 4])
np.linalg.norm(arr)

5.0

In [46]:
# L1-norm
np.linalg.norm(arr, ord= 1)

7.0

In [ ]:
arr2 = np.array([[1, 2], [3, 4]])
np.linalg.norm(arr2) # sqrt(1^2 + 2^2 + 3^2 + 4^2)

5.477225575051661

**Cosine similarity**

In [48]:
np.dot(A, B) / (np.linalg.norm(A) * np.linalg.norm(B))

0.9838699100999074