# Numpy
Numpy is an important scientific package for working with data. <br>
Many other packages are developed based on the numpy package. <br>
<br>
To install numpy, use the pip command:<br>
```bash
pip install numpy
```


In [287]:
import numpy as np

## Array definition
An array is a ndarrays objects. <br>
numpy arrays are defined as lists or lists of lists

In [288]:
a = np.array([[1,2], [3,4]])
print (f"a = {a} \ndata type: {a.dtype}\ndimention: {a.ndim}") #data type of elements and Number of array dimensions

a = [[1 2]
 [3 4]] 
data type: int32
dimention: 2


You can also define a 2-dimensional array as a matrix. <br>
Numpy matrices are strictly 2-dimensional, while numpy arrays (ndarrays) are N-dimensional.<br>
Matrix objects are a subclass of ndarray, so they inherit all the attributes and methods of ndarrays.<br>
Using ndarrays is prefered because it is more general than matrix.


In [289]:
b = np.matrix([[1,2], [3,4]])
b

matrix([[1, 2],
        [3, 4]])

Define special kinds of arrays:

In [290]:
# Define all-ones array
x = np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [291]:
# Define all-zeros array
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [292]:
# Generate an integer vector containing a sequence number from 0 to n-1
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [293]:
# Generate an integer vector using a sequence number from start (inclusive) to stop (exclusive), in steps
np.arange(1, 10, 3)

array([1, 4, 7])

In [294]:
# Generate a float sequence over a specified interval
np.linspace(1, 10, 3) # start (inclusive), stop (inclusive), number of elements

array([ 1. ,  5.5, 10. ])

In [295]:
# Generate an array using a sequence number auto shape
reshaped = np.arange(12).reshape((3,4))
reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [296]:
# Revert the reshaping
#   Method-1:
reflat = reshaped.reshape(-1)
reflat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [297]:
# reshape() returns a view of the original data. Thus, if you modify the returned value, the original one is also changed.
reflat[0] = 100
print(reflat)
print(reshaped)

[100   1   2   3   4   5   6   7   8   9  10  11]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [298]:
#   Mthod-2:
reflat = reshaped.flatten()
reflat

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [299]:
# flatten() returns a copy of the original data. Thus, if you modify the returned value, the original one is not changed.
reflat[1] = 200
print(reflat)
print(reshaped)

[100 200   2   3   4   5   6   7   8   9  10  11]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [300]:
# Define a random array
r1 = np.random.randint(0, 5, (3,4))
r1

array([[2, 0, 1, 3],
       [4, 1, 4, 2],
       [0, 1, 4, 1]])

In [301]:
# Define a random array
np.random.rand(2, 3)

array([[0.76401389, 0.88997464, 0.32378277],
       [0.10400008, 0.53709489, 0.11336425]])

In [302]:
# Generate a randomm array using uniform distribution
# Parameters: Min value (inclusive),  Max value (inclusive), array shape
myRandomArray = np.random.uniform(1, 5, (2, 3)) # Min value = 1,  Max value = 5, shape = 2 \times 3
print("My random array = ", myRandomArray)

My random array =  [[3.53174954 4.74151881 2.27242666]
 [1.0331061  1.66060189 3.04284131]]


In [303]:
# Generate a randomm matrix using normal distribution (mean=0, stdev=1).
myRandomArray = np.random.standard_normal((2, 3))
print("My random array = ", myRandomArray)

My random array =  [[ 0.72539325  0.4144149   1.39705243]
 [ 0.15674227 -1.8433776  -1.28457246]]


In [304]:
# Sets as arrays
aa = np.array([1,2,3,4,1,3])
print("unique values: ", np.unique(aa))

unique values:  [1 2 3 4]


In [305]:
# Union and Intersection of sets as arrays
bb = np.array([7,8,9,1,3])
print("The first set=", aa)
print("The 2nd array =", bb)
print("union = ", np.union1d(aa, bb))
print("Intersection = ", np.intersect1d(aa, bb))

The first set= [1 2 3 4 1 3]
The 2nd array = [7 8 9 1 3]
union =  [1 2 3 4 7 8 9]
Intersection =  [1 3]


## Shape and type

In [306]:
# Get size
print(a)
np.size(a)

[[1 2]
 [3 4]]


4

In [307]:
# Get shape
np.shape(a)

(2, 2)

Numpy data types and their corresponding types in C are as follows:<br>
| NumPy   | Equivalent C type                                                                 |
|:--------|:-------------------------------|
| float64 | double                         |
| float32 | float                          |
| int64   | long long [–2^63, 2^63−1]      |
| uint64  | unsigned long long [0, 2^64−1] |
| int32   | long [–2^31, 2^31−1]           |
| uint32  | unsigned long [0, 2^32−1]      |
| uint8   | unsigned char [0, 255]         |

In addition to numerical types, NumPy also supports strings
- unicode strings, via the numpy.str_ dtype (U character code), 
> - null-terminated byte sequences via numpy.bytes_ (S character code), and 
> - arbitrary byte sequences, via numpy.void (V character code).

Discussion about these types is out of the scope of this course!

In [308]:
z = np.array([1,2,3,4], dtype="uint8")
print ("z = ", z, "data type: ", z.dtype)

z =  [1 2 3 4] data type:  uint8


## Indexing

In [309]:
print("a = \n", a)
print("a[0, 1]= ", a[0,1])
print("a[1]= ", a[1])
print("a[0,0], a[1,0], a[1,1] = ", np.array([a[0,0], a[1,0], a[1,1]]))
print("a[[0,1,1], [0,0,1]] = ", np.array(a[[0,1,1], [0,0,1]])) # same as previous

a = 
 [[1 2]
 [3 4]]
a[0, 1]=  2
a[1]=  [3 4]
a[0,0], a[1,0], a[1,1] =  [1 3 4]
a[[0,1,1], [0,0,1]] =  [1 3 4]


## Slicing

In [310]:
b = np.arange(1, 13).reshape((4,3))
print("b= ", b)
print("b[1,:]= ", b[1,:])
print("b[:,1]= ", b[:,1])
print("b[:2,:]= ", b[:2,:])
print("b[:2,:2]= ", b[:2,:2])
print("b[:1,:1]= ", b[:1,:1])

b=  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b[1,:]=  [4 5 6]
b[:,1]=  [ 2  5  8 11]
b[:2,:]=  [[1 2 3]
 [4 5 6]]
b[:2,:2]=  [[1 2]
 [4 5]]
b[:1,:1]=  [[1]]


## Stepping

In [311]:
print("b= ", b)
# Stepping in rows
print("b[::2]= ", b[::2]) # The 3rd number is the step
print("b[::3]= ", b[::3])
print("b[::-2]= ", b[::-2]) # reverse order + steps

b=  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b[::2]=  [[1 2 3]
 [7 8 9]]
b[::3]=  [[ 1  2  3]
 [10 11 12]]
b[::-2]=  [[10 11 12]
 [ 4  5  6]]


In [312]:
print("b= ", b)
# Stepping in columns
print("b[:, ::2]= ", b[:, ::2])

b=  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b[:, ::2]=  [[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


In [313]:
print("b= ", b)
# Stepping in both sides
print("b[::-2, ::2]= ", b[::-2, ::2])

b=  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b[::-2, ::2]=  [[10 12]
 [ 4  6]]


## Member modification

In [314]:
q = np.arange(24).reshape((4,3,2))
print("q=\n", q)

q=
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [315]:
q[1,:,:] = [[66,77],[88,99],[100,111]]
print("updated q(1)=\n", q)

updated q(1)=
 [[[  0   1]
  [  2   3]
  [  4   5]]

 [[ 66  77]
  [ 88  99]
  [100 111]]

 [[ 12  13]
  [ 14  15]
  [ 16  17]]

 [[ 18  19]
  [ 20  21]
  [ 22  23]]]


In [316]:
q[2,...] = [[122,133],[144,155],[166,177]] # ... means as many : as needed
print("updated q(2)=\n", q)

updated q(2)=
 [[[  0   1]
  [  2   3]
  [  4   5]]

 [[ 66  77]
  [ 88  99]
  [100 111]]

 [[122 133]
  [144 155]
  [166 177]]

 [[ 18  19]
  [ 20  21]
  [ 22  23]]]


## Maths on array items

In [317]:
print("a=", a)
# Add arrays
a + a # or np.add(a, a)

a= [[1 2]
 [3 4]]


array([[2, 4],
       [6, 8]])

In [318]:
# Subtract arrays (two ways)
a - a # or np.subtract(a, a)

array([[0, 0],
       [0, 0]])

In [319]:
# Element to element multiplication: [ 1*1, 2*2], [3*3, 4*4]]
a * a # or np.multiply(a, a)

array([[ 1,  4],
       [ 9, 16]])

In [320]:
# divide each element to an scalar
print ("a / a = ", a / 2) # or np.divide(a, 2)

# divide element-by-elemnt of two matrices
d= np.array([[2,3],[4,5]])
print ("a / d = ", a / d) # or np.divide(a, d)

# The largest integer smaller or equal to the division of the inputs.
print ("a / 2 (floor) = ", np.floor_divide(a, 2)) 

a / a =  [[0.5 1. ]
 [1.5 2. ]]
a / d =  [[0.5        0.66666667]
 [0.75       0.8       ]]
a / 2 (floor) =  [[0 1]
 [1 2]]


In [321]:
# Scalar to array operations
farenheit = np.array([0, 10, -5, 4])
celcius = (farenheit - 31) * (5/9)
print("celcius = ", celcius)

celcius =  [-17.22222222 -11.66666667 -20.         -15.        ]


In [322]:
# Boolean arrays
print(celcius < -15) # it also works for the multi-dimentional arrays in the same way

[ True False  True False]


## Matrix multiplication
matrix product: sum of the multiplication of row elements to column element<br>
Example: $a \times a = [[1\times 1 + 2\times 3, 1\times 2 + 2\times 4], [3\times 1 + 4\times 3, 3\times 2 + 4\times 4]]$<br>
The operator is @, however you can also use dot function of numpy to get the product of 2D arrays. (More explanasion is out of the scope of this course!)

In [323]:
print("a@a = ", a@a)
print("np.dot(a, a) = ", np.dot(a, a))

a@a =  [[ 7 10]
 [15 22]]
np.dot(a, a) =  [[ 7 10]
 [15 22]]


## Matrix Inverse

In [324]:
org = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
# org = np.array([[1, 2], [3, 6]]) Sample array to test zero determinant
det = np.linalg.det(org)
if det == 0:
    print("Inverse doesn't exist. Determinant  is zero.")
else:
    print("determinant = ", det)
    print(np.linalg.inv(org))

determinant =  -306.0
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


## Aggregation functions

In [325]:
# Sum of all elemts
a.sum()

10

In [326]:
# Cumulative sum
print(a)
print ("Cumulative sum of the elements in array a= ", a.cumsum())
print ("Cumulative sum (axis=0) of the elements in array a= ", a.cumsum(axis=0))
print ("Cumulative sum (axis=1) of the elements in array a= ", a.cumsum(axis=1))

[[1 2]
 [3 4]]
Cumulative sum of the elements in array a=  [ 1  3  6 10]
Cumulative sum (axis=0) of the elements in array a=  [[1 2]
 [4 6]]
Cumulative sum (axis=1) of the elements in array a=  [[1 3]
 [3 7]]


In [327]:
# Multiplication of all elements: 1*2*3*4
a.prod()

24

In [328]:
# Max, min, mean
print (f"for a, Max = {a.max()}, Min = {a.min()}, Mean = {a.mean()}")

for a, Max = 4, Min = 1, Mean = 2.5


## Filtering

In [329]:
my_mask = a > 1
print("mask = ", my_mask)
print("a > 1 mask -> ", a[my_mask])
my_mask = np.logical_and(a > 1, a < 3)
print("1 < a < 3 mask -> ", a[my_mask])

mask =  [[False  True]
 [ True  True]]
a > 1 mask ->  [2 3 4]
1 < a < 3 mask ->  [2]


## Broadcasting

In [330]:
f = np.array([1, 2, 3])
x = np.ones((3, 3))
print("[1, 2, 3] + 5 = " , f + 5)
print("[1, 1, 1], [1, 1, 1] [1, 1, 1] + [1, 2, 3] = " , x + f)
print("[1], [1], [1], + [1, 2, 3] = " , np.array([[1], [1], [1]]) + f)

[1, 2, 3] + 5 =  [6 7 8]
[1, 1, 1], [1, 1, 1] [1, 1, 1] + [1, 2, 3] =  [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[1], [1], [1], + [1, 2, 3] =  [[2 3 4]
 [2 3 4]
 [2 3 4]]


## Using arrays as polynomials

In [331]:
# x^2 + 2x + 2
myPoly = np.array([1, 2, 2]) # Coefficient from largest to smallest
# Evaluate at specific value
print("2^2 + 2*2 + 2 = ", np.polyval(myPoly, 2)) # 1^2 + 2*1 + 2
print("derivation of (x^2 + 2x + 2) = ", np.polyder(myPoly)) # derivation(x^2 + 2x + 2) = 2x + 2
print("Integral of (x^2 + 2x + 2) = ", np.polyint(myPoly)) # integral(x^2 + 2x + 2) = x^3/3 + x^2 + 2x + 0

2^2 + 2*2 + 2 =  10
derivation of (x^2 + 2x + 2) =  [2 2]
Integral of (x^2 + 2x + 2) =  [0.33333333 1.         2.         0.        ]


In [332]:
# The privious cell use and old polynomial API 
# The newer one is as follows:
myPoly = np.polynomial.Polynomial([2, 2, 1]) # Coefficient from smallest to largest
myPoly

Polynomial([2., 2., 1.], domain=[-1,  1], window=[-1,  1], symbol='x')

In [333]:
# Evaluate at specific value
np.polynomial.polynomial.polyval(2, np.array([2, 2, 1]))

10.0

In [334]:
# derivation
myPoly.deriv()

Polynomial([2., 2.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')

In [335]:
# Integral
myPoly.integ()

Polynomial([0.        , 2.        , 1.        , 0.33333333], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')

In [336]:
# Save and load to/from file
print("r1= ", r1)
np.save("random.npy", r1) # It is a binary file
r2 = np.load("random.npy")
print("r2= ", r2)

r1=  [[2 0 1 3]
 [4 1 4 2]
 [0 1 4 1]]
r2=  [[2 0 1 3]
 [4 1 4 2]
 [0 1 4 1]]


In [337]:
# Delete as usual
import os
os.remove('random.npy')

## Others

In [338]:
# Related numpy fuctoins to the following functions were deprecated.
# Since the functions are migrated to the standard math package, we use them as follows:

# Square root
import math
print ("sqrt of 5= ", math.sqrt(5))

# Not a number -> application = missing values
y = math.nan
print("y = ", y)

# Infinity
print("Infinity = ", math.inf)


sqrt of 5=  2.23606797749979
y =  nan
Infinity =  inf
